import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import About from "~/components/sections/About";
import Explore from "~/components/sections/Explore";
import Feedback from "~/components/sections/Feedback";
import GetStarted from "~/components/sections/GetStarted";
import Hero from "~/components/sections/Hero";
import Insights from "~/components/sections/Insights";
import WhatsNew from "~/components/sections/WhatsNew";
import World from "~/components/sections/World";
import Footer from "~/components/ui/Footer";
import Navbar from "~/components/ui/Navbar";
import { api } from "~/utils/api";
import stamp from "~/public/SHEHZAD.png";

const Home = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Shehzad Munir</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href={stamp.src} />
      </Head>
      <div className="overflow-hidden bg-primary-black">
        <Navbar />
        <Hero />
        <div className="relative">
          <About />
          <div className="gradient-03 z-0" />
          <Explore />
        </div>
        <div className="relative">
          <GetStarted />
          <div className="gradient-04 z-0" />
          <WhatsNew />
        </div>
        <World />
        <div className="relative">
          {/* <Insights /> */}
          <div className="gradient-04 z-0" />
          <Feedback />
        </div>
        <Footer />
      </div>
    </>
  );
};

export default Home;
